configuration:
  exchange:
    pair_blacklist:
      # STRAT SPECIFIC
      # Leverage
      - ".*(UP|DOWN)/.*"
      - ".*(HEDGE|HALF|_PREMIUM|BEAR|BULL|HALF|HEDGE|[1235][SL]).*/.*"
      - ".*PERP"
      # Fiat
      - "^(AED|ARS|AUD|BRL|BRZ|CAD|CHF|CZK|DKK|EUR|GBP|GHS|HKD|IDRT|HUF|JPY|KES|KZT|MXN|NGN|NOK|NZD|PEN|PLN|RUB|SGD|SEK|TRY|UAH|USD|UGX|VND|ZAR)/.*"
      # Stable
      - "(BUSD|BIDR|BVND|CUSDT|DAI|PAX|PAXG|SUSD|TUSD|USDC|USDT|USDS|VAI)/.*"
      # FAN
      - "^(ACM|AFA|ALA|ALL|APL|ASR|ATM|BAR|CAI|CITY|FOR|GAL|GOZ|IBFK|JUV|LEG|LAZIO|LOCK-1|NAVI|NMR|NOV|OG|PFL|PORTO|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*"
